### PR TITLE
bugfix

### PR DESCRIPTION
**Pull request by kiwi0fruit**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kiwi0fruit** [comment]
@ocefpaf please PR

**Comment by kiwi0fruit** [comment]
@ocefpaf By the way: such bugs are reported on Windows CI but not in Linux CI.

**Comment by ocefpaf** [comment]
> @ocefpaf By the way: such bugs are reported on Windows CI but not in Linux CI.

Maybe we shoulf investigate if there are any platform specific things on the code to be sure this package can be `noarch`. I'll leave that to the jupyter team who is more familiar with the code than me.

**Comment by kiwi0fruit** [comment]
@ocefpaf I'm sure that is can be noarch. Do not worry. I suspect that it's the behaviour of the conda build that spots .exe entry points and reports  them with error. But conda build cannot spot unix entry points and report them.

You are safe to PR this. But whom should I ping to about lack of entry points checking on unix?

**Comment by ocefpaf** [comment]
Ah OK. So we were only missing the entrypoint specification. Let's merge this then. Thanks!

**Pull request merged**
