### PR TITLE
Release 5.2.0

### PR DESCRIPTION
**Pull request by takluyver**

### CODE REVIEW

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

Should fix Windows

**Comment by takluyver** [comment]
I just made it a noarch package and rerendered manually.

**Comment by takluyver** [comment]
It seems conda isn't handling entry points quite right:

```python
from jupyter_client.kernelspecapp import KernelSpecApp.launch_instance
```

Would turning noarch back off work around this issue?

**Comment by ocefpaf** [comment]
> I just made it a noarch package and rerendered manually

That is probably it.

**Comment by minrk** [comment]
@takluyver I think you're right. I don't think noarch packages can be used if there are entrypoints for now.

**Comment by takluyver** [comment]
And for some reason it seems that Appveyor hasn't come back when I turned noarch off again. :-/

**Comment by ocefpaf** [comment]
> And for some reason it seems that Appveyor hasn't come back when I turned noarch off again. :-/

We are probably rate limited for now. We need to wait a few minutes before trying again :unamused:

**Comment by jakirkham** [comment]
Nudged AppVeyor. Seems to be running now. May very well have been rate limited before.

**Comment by takluyver** [comment]
Thanks :-)

**Comment by minrk** [comment]
All green!

**Comment by jakirkham** [comment]
FWIW here is the relevant AppVeyor issue ( https://github.com/appveyor/ci/issues/1002 ) for the rate limiting problems we experience.

**Comment by jakirkham** [comment]
So is `pytest` now a `run` requirement? Just saw this (please note the last line in particular)...

```python
jupyter-nbextensions_configurator enable --sys-prefix
Traceback (most recent call last):
  File "/opt/conda3/bin/jupyter-nbextensions_configurator", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/opt/conda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3144, in <module>
    @_call_aside
  File "/opt/conda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3128, in _call_aside
    f(*args, **kwargs)
  File "/opt/conda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3157, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/conda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "/opt/conda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/conda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pytest; python_version >= "3.4" or python_version == "2.7" and extra == "test"' distribution was not found and is required by jupyter-client
```

**Comment by takluyver** [comment]
No, it's only required for testing. You've got a wrapper script that's been written by setuptools. I recommend using `pip install` rather than `setup.py install` for all installation (/conda recipes) to avoid this.

**Comment by jakirkham** [comment]
Will raise with the `jupyter_nbextensions_configurator` folks then. In any event, am not running into the issue with `5.1.0`.

**Comment by jakirkham** [comment]
Raised as issue ( https://github.com/conda-forge/jupyter_nbextensions_configurator-feedstock/issues/21 ).

**Comment by jmsdnns** [comment]
I managed to work this out for the beakerx project. The issue is that the error message is not consistent with what the error actually is, misleading us.

Take a look at the error message. It tells us that the Python version isn't found, but also notice that the very first thing in the quoted text is `pytest`. If pytest is not installed, the `DistributionNotFound` error is thrown with text talking about python versions and barely mentioning pytest.

```pkg_resources.DistributionNotFound: The 'pytest; python_version >= "3.4" or python_version == "2.7" and extra == "test"' distribution was not found and is required by jupyter-client```

To be clear, switching to pip for conda recipe does not fix this issue. Adding `pytest` as a dependency for both the build and run requirements fixes the issue.

Example: https://github.com/twosigma/beakerx-feedstock/blob/master/recipe/meta.yaml#L24

**Comment by jmsdnns** [comment]
A little more context: I initially tried `pytest` as a requirement for just build but this failed. I added it to build and run and then it worked.

**Pull request merged**
