### PR TITLE
Add entrypoints, refresh deps

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin, please rerender

**Comment by bollwyvl** [comment]
Hooray, it built:

```
============ 161 passed, 4 skipped, 1 warning in 146.63s (0:02:26) =============
+ exit 0

# Automatic uploading is disabled
# If you want to upload package(s) to anaconda.org later, type:


# To have conda build upload to anaconda.org automatically, use
# conda config --set anaconda_upload yes
anaconda upload \
    /home/conda/feedstock_root/build_artifacts/noarch/jupyter_client-7.0.1-pyhd8ed1ab_1.tar.bz2
anaconda_upload is not set.  Not uploading wheels: []

INFO :: The inputs making up the hashes for the built packages are as follows:
{
  "jupyter_client-7.0.1-pyhd8ed1ab_1": {
    "recipe": {
      "channel_targets": "conda-forge main"
    }
  }
}
```

However, since we never actually shipped `build: number: 0`, we can bump that back down...

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
We can follow up on a separate PR/release to change maintainership. Thanks all!

**Comment by blink1073** [comment]
Thanks @bollwyvl!  :rose:

**Comment by bollwyvl** [comment]
Huzzah: build actually up: https://anaconda.org/conda-forge/jupyter_client/files?version=7.0.1

```
noarch/jupyter_client-7.0.1-pyhd8ed1ab_0.tar.bz2
```

CDN will take a bit, but I think we're good now....

**Pull request merged**
