### PR TITLE
5.3.4 (with updated meta and tests)

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

alternative to #32.

This:
- adds some deps from upstream
- adds tests
- updates some metadata
- sorts things
- adds myself to maintainer list

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
All right: with the dirty trick of skipping the win/py38 tests entirely, this looks good to go!

**Comment by bollwyvl** [comment]
Presumably when ipykernel comes out clean on that combination, we can revisit:
https://github.com/ipython/ipykernel/pull/456

**Comment by mbargull** [comment]
blocks https://github.com/conda-forge/spyder-kernels-feedstock/pull/42

**Pull request merged**
